name: CI

on: [push]

jobs:
  pjlib-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: apt-get install -y build-essential gcc-multilib curl qemu-system-x86
      - name: confload
        run: make confload-x86/qemu
      - name: build
        run: make -j $(nproc)
      - name: pjlib-test
        run: timeout 60 ./scripts/qemu/auto_qemu
